### PR TITLE
WIP Feature/78/historical user overview

### PR DESCRIPTION
**Pull request by Silox**
WIP for #78 

Todo:
- [x] Put @Procrat's tweaks back
- [x] add an annotationchart for scores
- [x] add detailed logs of commits and claimed bounties

### CODE REVIEW

**Comment by Silox** [comment]
Current progres:

Commit history:
screen shot 2015-09-06 at 17 10 00

Bounty history:
screen shot 2015-09-06 at 18 39 58

**Comment by Silox** [comment]
@Procrat I disabled the filter infomation in the left down corner for the scoreboard. I also updated the jquery-datatables-rails gem a minor version, this now results in a cleaner search (some whitespace) and more clear sorting icons: 

screen shot 2015-09-06 at 21 15 51

Scoreboard remains like it was before, with only the changed sorting icons. 

Are you satisfied with this amount of clutter, or should I reduce it for the bounties page?

**Comment by Procrat** [comment]
Yeah, that "information" part ("Showing x to y of z entries (filtered from q total entries)") makes sense for statistical pages like these. I'm gonna remove it from the bounties page, though, if you don't mind. Same for the "Show X entries" part IMHO. We can discuss about all this if you want.

**Comment by Procrat** [comment]
I appear to have a horizontal scrollbar.

**Comment by Procrat** [comment]
This is cool; it let's you reposition and add/remove parts of the datatable elements. http://datatables.net/examples/basic_init/dom.html

**Comment by Procrat** [comment]
Heh, both Bootstrap and DataTables use the "row" class, which causes that scrollbar glitch.

**Comment by Silox** [comment]
Graphs! :o 

screen shot 2015-09-10 at 15 09 24

**Comment by Silox** [comment]
Finished :3 Pls review @Procrat or @iasoon

**Comment by Procrat** [comment]
Looks very good to me! ^^

**Pull request merged**
