### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### ZeusWPI/gamification now has a Chat Room on Gitter

@Procrat has just created a chat room. You can visit it here: [https://gitter.im/ZeusWPI/gamification](https://gitter.im/ZeusWPI/gamification?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/ZeusWPI/gamification?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by Procrat** [comment]
O_O
I did what know

**Comment by Silox** [comment]
You made the gitter channel so Gitter sends a PR to add the badge to the readme :D



On 21 Aug 2015 at 11:23:41, Stijn Seghers (notifications@github.com) wrote:

O_O
I did what know

**Comment by Procrat** [comment]
Scary.

**Comment by Procrat** [comment]
Not doing this atm.

**Pull request closed without merging**
